### ISSUE TITLE
Local content managers should not be able to see the link 'Newsletter to list' at all in their admin window

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#119]

**Comment by trolando** [comment]
The reason they see this now, is due to having the permission to create such objects. This permission is required to use the "Send to list" link on the Newsletter admin. I can replace the required permission by a custom permission "hemres_send_to_list".

**Comment by trolando** [comment]
Fixed in next Hemres release, but also requires modification of jd finalize script

**Comment by trolando** [comment]
Fixed in ca20bcf9c9aae6ce287b115c05c386a3a601c195

**Comment by Pieter1024** [comment]
I would contend that a better way is to add an in_admin function to the NewsletterToListAdmin. This function checks whether the user has the modification permission for NewsletterToList and only then returns True (I.e. only then is the admin tab visible).

The reason I think this is better is because a) it keeps our permission model simple and b) it actually does what we want (I.e. hide the tab from some people) and nothing else.

A similar approach could solve issue #126, by hiding the tabs from users who do not have the associated modification permissions.

**Comment by Pieter1024** [comment]
@trolando I would appreciate your view on my proposal (especially since it affects Hemres code) before I implement it (or you do that).

**Comment by trolando** [comment]
I suppose that also works. Wont be home until the evening. Was not aware of this option. Will revert commits in Hemres then since not adding special permissions has higher priority than splitting the two permissions.

**Comment by trolando** [comment]
It doesn't work quite this way. For example, there is no in_admin function.

There is has_module_permission(), but if I let this return False, this has not the desired result for the following reason, that even only an "add" permission is sufficient to show up in the list.

What does work, is overriding has_add_permission as follows:
```
def has_add_permission(self, request):
    if not super(NewsletterToListAdmin, self).has_add_permission(request):
        return False
    return True if self.has_change_permission(request) or self.has_delete_permission(request) else False
```

Then, a user only has add permission in the admin if they also have change and delete permission.

I'm still not sure which option is the ugly hack, though. What does it mean to have "add permission"? I could say, it now means "can add newslettertolist objects via the standard admin interface and can add newslettertolist objects via the button Send to List", whereas the custom permission would separate these two actions. As to maintaining and complexity, both methods add some complexity; my original solution separates the two methods of creating newslettertolist objects using a custom permission for the non-standard route, while this method modifies the expected behavior that someone who can add newslettertolist objects has access to the Add admin for those objects.

**Comment by trolando** [comment]
Anyway, both options have the desired effect now. We just have to choose which one we want to use.

**Comment by trolando** [comment]
Very deep inspection of Mezzanine revealed a check for model_admin.in_menu()

So, I don't really need to modify has_add_permission, I can just modify in_menu instead. Still modifies the expected behavior, though.

**Comment by Pieter1024** [comment]
Yes, I'm sorry for the in_admin confusion, it should be in_menu. Documentation for that is at http://mezzanine.jupo.org/docs/admin-customization.html#navigation.

I prefer the in_menu option, as this is the most properly documented.

**Comment by trolando** [comment]
Yes, but in_menu does not give any parameters, and we need the request to determine the user, and we need the user to figure out if they have the right permissions.

**Comment by Pieter1024** [comment]
The core of the problem is that the models users may not change are listed in the dropdown menu. This, I think, is due to a bug in Mezzanine. I submitted a patch to fix it: https://github.com/stephenmcd/mezzanine/pull/1433.

**Comment by trolando** [comment]
While that patch would solve the broken "Noneadd/" link, the point here is that if the user has an Add permission, that link will let them Add a new NewsletterToList object. We don't want them to be able to do that if they are not in the Administrators group. We want Content Managers to go to the list of the Newsletters of their site, then click the "Send to List" hyperlink, choose the Mailinglist there, and press a confirmation button.

In order to remove the option of Adding NewsletterToList objects, we are still limited to ~~two~~ three options: either a separate permission for the "Send to List" hyperlink, or use the hemres.add_newsletter for that permission ("if you can add newsletters, then you can also prepare sending to a mailinglist"), or break the default behavior of the admin by overriding has_add_permission in the model admin.

**Comment by Pieter1024** [comment]
Or override the template, to include some CSS that disables the visibility of any <a href='/admin/hemres/newslettertolist/'>-type link if the user does not have the change permission. I mainly propose this idea because I understand it better than the options you've put forward :).

**Comment by trolando** [comment]
All four options would work. The question is which option is clean, maintainable, and simple to explain.

So, what we want is that normal Content Managers do not have permission to use the manual "add NewsletterToList" form, but we do want them to have permission to use the "Send to List" functionality.

Options:
1) Create a separate permission for "Send to List".
2) Imply the permission for "Send to List" by the permission to add a Newsletter.
3) Override default Model Admin behavior to remove the add permission if the user does not have change or delete permissions on NewsletterToList.
4) Override the template to hide the link.

Against the first option, introducing a new permission adds complexity.

Against the second option, it may not be clear that having permission to add newsletters also implies having permission to initiate sending.

Against the third option, it really is a hack that breaks expected functionality. What it does is "yes you have add permissions, but we override this if you don't have change/delete permissions".

Against the fourth option, this is even more a hack than the third option, and is more counterintuitive.

I think option two makes most sense, followed by option one. I don't even know why we're considering option four, I don't think CSS should be used to implement functionality.

**Comment by Pieter1024** [comment]
Thank you for explaining this so thoroughly. Given this information, I prefer option two as well. The reason is that it makes functional sense. The ability to send a newsletter should be a part of creating it. Just saving it without sending it is possible, but ultimately a newsletter is 'done' when it is sent.

Given that we both prefer this option, could you implement it? I believe we currently use option one?

**Comment by trolando** [comment]
Yes, it will be updated shortly.

**Comment by trolando** [comment]
It is updated in the rolling release 0.8. Eh, the migration script "should" be rerun to remove the stale permission, but its presence won't harm anyone.

**Comment by Pieter1024** [comment]
Excellent!

**Comment by Pieter1024** [comment]
I've run the migration script as well, so the stale permission should be gone by now.
