### ISSUE TITLE
Local content managers should only be able to view their own admin backend, not those of others

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#120]

**Comment by trolando** [comment]
Janeus was designed to handle this.

If this does not work, how do I reproduce the error?

For example, someone with only the LDAP group "role-as-friesland" will only get the JaneusRole associated with that group, which has a restriction on the available sites: only friesland.jongedemocraten.nl. So they only get SitePermission for that site. And only the permissions associated with the group Content Managers.

Do you have a test case that currently fails?

**Comment by Pieter1024** [comment]
My test case was someone who used to be role-team-ict (e.g. me) and was degraded (from a permissions perspective :) ) to role-as-brabant. I will gladly change your role if you are testing online so that you can experience/check what is going on.

**Comment by Pieter1024** [comment]
Let's coordinate via IRC to ensure timely changes. I am online the next 40 minutes.

**Comment by trolando** [comment]
So, as per phone, the issue is not that someone who has a stale SitePermission can login on an admin site per se, but that the Media Library is not protected by permissions.

This means that if we grant a user any permission on the site, then they also have full access to the Media Library. I think this is a serious flaw, even if we tell Janeus to reset the SitePermissions every login, which is certainly something that is easy to program.

I submitted an issue to filebrowser_safe with an example how such permissions could be added.

In the meantime, I suppose we'll just have to accept the fact that anyone with any right on a site can seriously mess with the media library, and reset all site permissions every time a user logs in...

**Comment by Pieter1024** [comment]
Agreed. Do you have a link to the issue you submitted to filebrowser_safe?

**Comment by trolando** [comment]
Yes, the issue can be found here: https://github.com/stephenmcd/filebrowser-safe/issues/52

**Comment by trolando** [comment]
The site permissions are now reset every time a user logs in, fixed in 0066485dc17a65074ed1e6e37cd8d1e9b613ea65 (and in Janeus: https://github.com/jonge-democraten/janeus/commit/9ff48964eef71bfbece0a5360d750729d871abb8)

**Comment by Pieter1024** [comment]
I have verified that this works correctly. Thanks, @trolando !
