### ISSUE TITLE
Imported newsletters incorrect encoding

### ISSUE THREAD

**Issue by trolando** [jonge-democraten/website#130]
I noticed that the encoding of imported newsletters is incorrect, for example in https://website.jongedemocraten.nl/nieuwsbrief/view/621/

**Comment by Pieter1024** [comment]
I don't find it necessary to fix this, because:
* right now it's exactly the same in the old system, and this only concerns archived newsletters.
* they still display properly in my browser, so I suppose in many others as well.
* our task is 1) to recreate existing functionality and 2) to import existing content. This is out of scope.

If we want to do this, I would definitely not gauge it as 'should'.

**Comment by Pieter1024** [comment]
I'm closing this issue, as no-one seems to contest my objections. @trolando if you have a different view, please do reopen the ticket and share your thoughts.
