### ISSUE TITLE
Customizable sidebar

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#60]
Backend users of the different sites (departments) should be able to add a widget to the sidebar that shows social media buttons, blogcategories, banner, events, twitter, etc.

**Comment by Pieter1024** [comment]
This is a minor part of the larger issue of the sidebar content, which I believe is still open for debate.

All departments have sidebar content, but:
* not all departments have the same content items;
* not all departments have the same number of one type of content item;
* not all departments have the content items in the same order.

It is questionable whether we should offer all these degrees of freedom, mostly because it looks quite messy if all departments have their right sidebar content items in a different order.

I would propose:
* Each department has a right sidebar.
* This right sidebar consist of 0 or more blog blocks, 1 agenda/newsletter widget, 0 or 1 twitter widgets and 0 or 1 social media blocks. The department decides on the numbers of each element and which specific blogs/twitter accounts/social media accounts to highlight.
* This right sidebar also contains 0 or 1 banners that we may set centrally (compare 'Word lid!' on jd.nl). The department has no control over the number of banners or their content.
* We decide where the banner is on the right sidebar. Possible positions are:
  * Above blogs
  * Between blogs and agenda/newsletter widget
  * Between agenda/newsletter widget and twitter widget
  * Between twitter widget and social media buttons.
* It is not possible to influence the order of the different elements, other than deciding the place where the banner will be displayed.

In this way:
* departments decide on (most of the) content they wish to showcase;
* we achieve a consistent look among departments.

As always, open for ideas.

**Comment by bartromgens** [comment]
> This is a minor part of the larger issue of the sidebar content, which I believe is still open for debate.

Correct! :) 

I like your proposal. Departments are free to decide on the content of the sidebar, but the layout is not editable to give a consistent look among departments.

Each department has only one sidebar, correct? There is no page specific sidebar content?

**Comment by Pieter1024** [comment]
Yes.

**Comment by bartromgens** [comment]
A configurable right-sidebar is mostly implemented since commit 81158de497f251c8968e194c4db798d663fd4edb. 

The order of the sidebar items is fixed,
 * 0-2 blog category items
 * 0-1 twitter items
 * 0-n banners (these are global, not siterelated)
 * 0-1 social media items with 0-N buttons.  

It still needs a agenda and newsletter item. These can be added when the events and newsletter apps are finished. 

The sidebar is editable in the admin under 'Content'. 
It is currently possible to add multiple sidebars and make them 'active' or 'inactive'. 
This should be changed to a singleton sidebar per site. When clicking on the sidebar link, one should directly go to the site's sidebar edit view, instead of the sidebars list.

**Comment by bartromgens** [comment]
The sidebar admin view is now a SingletonAdmin, see commit 0075cab3dc7a2722e2218b396ed7c78893d744c1.

**Comment by Pieter1024** [comment]
It looks realllly good :)

**Comment by Pieter1024** [comment]
I gave demo users appropriate permissions on sidebars in commit 12c475bb130b309a755c9e1ac1393b548516865c.

**Comment by Pieter1024** [comment]
I tried to follow your instructions in the design document to create a tabs widget (for the upcoming events and the newsletter). The result is in branch feature/sidebartabs/#60.

I ran into problems when trying to run recreate_demodata_database.sh, I got some error about NOT NULL constraints. The 'new' part of the code is that this is the first widget that is compulsory and should therefore always be included exactly once. Normally, I would just put such code in the main sidebar code. However, all other widgets have been arranged so nicely, I didn't want to break that up.

@bartromgens, could you look into this? I believe it is an important missing piece to allowing @trolando and @sh4wn to finish their work.

**Comment by bartromgens** [comment]
I hopefully fixed this in commit 78044764ee6500971fbe6e0d712d364de21e7dec. 

The combination of loading fixtures, auto creating new models, and SiteRelated models, is a bit tricky. Not sure why this works and your version did not.

**Comment by Pieter1024** [comment]
After commit ce0cb2d76978556a382e689b26da01b595ac6378, the functional sidebar tabs widget is in the master branch.

Two tasks remain open in this issue:

* [ ] Add upcoming events content (@sh4wn ?)
* [ ] Add newsletter registration content (@trolando ?)

**Comment by trolando** [comment]
For the newsletter thing in principle I have written a method that sends an
email to an email address and this is all that the newsletter side bar
widget needs to call.
Op 3 apr. 2015 19:18 schreef "Pieter1024" <notifications@github.com>:

**Comment by Pieter1024** [comment]
I completed the upcoming events tab in the sidebar. It is now available in the master branch.

Since it involved some changes to the template tags of mezzanine-fullcalendar, a ./clean_env will be necessary to see the changes.

The only remaining part here is the content that @trolando will add to the second tab, and I believe that is already available in the hemres branch. If he moves that content to the master branch, this issue can be closed.

**Comment by Pieter1024** [comment]
The newsletter registration is now in the master branch. I'm closing this issue.
