### ISSUE TITLE
Twitter feeds on homepages of departments

### ISSUE THREAD

**Issue by Pieter1024** [jonge-democraten/website#7]

**Comment by Pieter1024** [comment]
@bartromgens, you probably want to clean up/incorporate my code into your view on templates. More specifically, I think you want to put the CSS somewhere in the repository (it currently loads from the jd.nl website) and place the inline CSS in there as well. Feel free to do so and then merge the result into master.

**Comment by bartromgens** [comment]
I'm still open to where to put the CSS files, but since they are intertwined with our templates, that makes most sense to me. I will look at your templates and add the CSS. We can always remove them later. I prefer to have a standalone repo during initital development. 

Do you know who created our templates? And whether they are generated from some other source (SASS) or manually created? Do they implement a Joomla theme? I have almost zero knowledge about our current website. 

In the long term, it may make more sense to switch to a more generic, customizable and open CSS framework/them like bootstrap. This allows for easy switching between themes without changing the Django templates. And it provides a mobile view. Something for later though.

**Comment by Pieter1024** [comment]
Information on the template of the previous website is at http://jongedemocraten.nl/templates/jd/templateDetails.xml. I am pretty sure it was developed specifically for JD, but I am not entirely sure. Perhaps @bashazeborg can shed some light on that.

The layout of the Twitter feed is taken from the module used to make it, namely http://extensions.joomla.org/extensions/extension/social-web/social-display/twitter-widget. We customised it to our own color scheme, using the inline CSS that I included.

**Comment by Pieter1024** [comment]
Come to think of it, @floort was already around back then. Perhaps he knows.

**Comment by floort** [comment]
I don't know how ownership and licences of the files is arranged. Maybe @bashazeborg can find the old contracts? Otherwise: expect the worst and assume we don't own copyright.

**Comment by bashazeborg** [comment]
I''ll take a look on wednesday! Will the big pull-day then!

Met vrijzinnige groet,

Bas Hazeborg

--

Landelijk Bestuur der Jonge Democraten
Algemeen Secretaris

Telefoon: 06 38977320
E-mailadres: secretaris@jongedemocraten.nl

2015-01-11 17:43 GMT+01:00 Floor Terra <notifications@github.com>:

**Comment by Pieter1024** [comment]
I have merged the branch introducing Twitter feeds into master. Note when testing: the default search works without an API key, but when you want to use a different search (e.g. 'jongedemocraten'), your own API key is needed. I have tested this by hand and it works :).

**Comment by bartromgens** [comment]
Good! 

Reminds me that I would add the CSS to the repository. 

The twitter CSS is a modified version of the http://extensions.joomla.org/extensions/extension/social-web/social-display/twitter-widget Joomla widget CSS with GPL license. Although the CSS alone is short and general enough that I believe we can add this to our repository with a MIT license.
