### ISSUE TITLE
Trainers page with expand/collapse section

### ISSUE THREAD

**Issue by bartromgens** [jonge-democraten/website#72]
See http://jongedemocraten.nl/scholing-vorming-1/trainers.html.

Is it possible to create this in a normal Mezzanine RichTextPage?

**Comment by Pieter1024** [comment]
Probably not. The onclick attribute is not one of the whitelisted attributes in the RICHTEXT_ALLOWED_ATTRIBUTES setting. Also, the script tag is filtered because it is not in the whitelisted RICHTEXT_SCRIPT_TAG_WHITELIST setting.

This is a problem and should probably be fixed.

**Comment by Pieter1024** [comment]
This now works. I have fixed this in the following way:

* Make a new JS file, /static/website/js/jdshowhide.js, that contains the necessary code.
* Whitelist this file in settings.py for inclusion in rich text fields.

In order to make a show/hide functionality, do the following:
* Include the JS file by adding `<script src="/static/website/js/jdshowhide.js" type="text/javascript"></script>` to the field.
* Mark the item to toggle by giving it an ID of the form 'A#'. For example: `<div id="A3">Toggled content</div>`.
* Mark the link that toggles the item by giving it a matching ID of the form 'jdtoggle-#'. For example, the div from the previous bullet would be toggled by `<a href="#" id="jdtoggle-3">this link</a>`.

**Comment by Pieter1024** [comment]
This should probably be documented in the admin/design documentation, but not in the user documentation. I wouldn't support it for casual use. Its usability is also not sufficient for such cases.
